### ISSUE TITLE
ES cluster

### ISSUE THREAD

**Issue by tchansen** [gcastellov/news-track#24]
With the three ES containers it seems like a bit more than I'd need for a personal aggregator. To decrease them, just remove one from the docker compose and adjust the back end service to use the remaining two?

Also, in the current docker compose it has 
`news-track-back:
    depends_on: [es02, es03]`

but doesn't include es01. Is this intentional?

**Comment by gcastellov** [comment]
Sorry for the late response. I think you are right. For development purposes does not make sense to have the 3 nodes. I will change the compose file with a single node approach.
